[package]
name = "epub-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "manga2epub"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
epub-core = { path = "../epub-core" }
rust-i18n = "4.2.1"
serde = { version = "1", features = ["derive"] }
sys-locale = "0.3.2"
yaml_serde = "0.10"

[dev-dependencies]
uuid = "1"
zip = { version = "7", default-features = false, features = ["deflate"] }
