[package]
name = "epub-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "manga2epub"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
epub-core = { path = "../epub-core" }
rust-i18n = "4.2.1"
sys-locale = "0.3.2"
